server:
  port: 8080
apollo:
  monitor:
    enabled: true
    protocol: Prometheus
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,application1,application2,application3
  config-service: http://81.68.181.139:8080
app:
  id: 0000097
logging:
   level:
     com.ctrip.framework.apollo: debug
