server:
  port: 8080
apollo:
  monitor:
    enabled: true
    protocol: Prometheus
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,app1,app2,app3
  config-service: http://81.68.181.139:8080
app:
  id: tikview
logging:
   level:
     com.ctrip.framework.apollo: debug
